name = "back-api-takeserver"
main = "src/worker.ts"
compatibility_date = "2026-07-10"

compatibility_flags = [ "allow_unsafe_eval" ]

workers_dev = true
preview_urls = true

[vars]
ENVIRONMENT = "production"
